name: Delete Old Workflows And Releases
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Back to Commit'
        required: false
        default: ''  
  schedule:
    - cron: 0 3 * * *

jobs:
  Cleaning:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      
    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 3
        keep_minimum_runs: 0

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
